In [1]:
import math

In [2]:
math.sqrt(25)

5.0

In [3]:
math.pi

3.141592653589793

In [4]:
import math as mt

In [5]:
mt.sqrt(25)

5.0

In [6]:
import numpy

In [7]:
import math

In [61]:
import stats from scipy

SyntaxError: invalid syntax (<ipython-input-61-8eecefd8e6be>, line 1)

In [41]:
import stats

ModuleNotFoundError: No module named 'stats'

In [24]:
import scipy

In [62]:
from scipy import stats

In [37]:
from numpy import random

In [26]:
import numpy as np

In [34]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [32]:
dataOne = random.rand(5,5)

In [20]:
import random

In [43]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [44]:
dataOne

array([[0.42494337, 0.4204598 , 0.77622808, 0.82958438, 0.76439264],
       [0.61983008, 0.32835616, 0.94570235, 0.88374956, 0.1799775 ],
       [0.37381906, 0.68718759, 0.95402258, 0.79025993, 0.25063355],
       [0.56405273, 0.33674926, 0.74297426, 0.68478637, 0.89030368],
       [0.16649614, 0.48886979, 0.03695252, 0.40182082, 0.15488289]])

In [47]:
np.mean(dataOne)

0.5478814037516696

In [51]:
math.fabs(-19)

19.0

In [55]:
math.cos(7698476126419264)

0.33618272557817974

In [58]:
math.tanh(876587618357175)

1.0

In [69]:
stats.tmean(dataOne)

0.5478814037516696

In [72]:
stats.argus(dataOne)

In [73]:
print('I Love data Science')

I Love data Science


In [75]:
print(dataOne)

[[0.42494337 0.4204598  0.77622808 0.82958438 0.76439264]
 [0.61983008 0.32835616 0.94570235 0.88374956 0.1799775 ]
 [0.37381906 0.68718759 0.95402258 0.79025993 0.25063355]
 [0.56405273 0.33674926 0.74297426 0.68478637 0.89030368]
 [0.16649614 0.48886979 0.03695252 0.40182082 0.15488289]]


In [76]:
# Variables
variableName = 25

In [77]:
variableName1 = 'I Love data Science'

In [78]:
print(variableName1)

I Love data Science


In [79]:
# Datatypes
type(variableName)

int

In [80]:
variableName = 25.0

In [81]:
type(variableName)

float

In [82]:
varOne = 25
varTwo = 25.0
varThree = varOne + varTwo
print(varThree)

50.0


In [83]:
varOne = 25
varTwo = 'Hello'
varThree = varOne + varTwo
print(varThree)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [92]:
# It is not possible to addand integer and a string.  Python is not able to use Implicit Conversion in such conditions. 
# However, Python has a solution for these types of situations which is known as Explicit Conversion.
# https://www.programiz.com/python-programming/type-conversion-and-casting

In [96]:
# List
listOne = [1,2,3,4]
print(listOne[1:3])

[2, 3]


[2, 3]


In [97]:
# Dictionary
tel = {'jack': 4098, 'sape': 4139}
tel['jack']

4098

In [98]:
# Practice

In [110]:
Dic = {'A': 21, 'B': 32, 'C': 43, 'D': 54, 'E': 65}
Dic ['C']

43

In [114]:
math.gcd(Dic['E'], Dic['A'])

1

In [119]:
math.frexp(Dic['B'])

(0.5, 6)

In [121]:
math.floor(Dic['C'])

43